### PR TITLE
dropping python2.6 support

### LINKED ISSUE #70: Drop Python 2.6 support
What about dropping Python 2.6 support after a new scrapely version is released, i.e. making scrapely 0.13.0 the last version which supports Python 2.6?

### PR DESCRIPTION
**Pull request by eLRuLL**
fixes #70

### CODE REVIEW

**Comment by pablohoffman** [comment]
I'm OK with dropping py2.6 support for scrapely

**Comment by kmike** [comment]
I think we should do it after making a last py26 release from the current code. See also: https://github.com/scrapy/scrapely/pull/77 :)

**Comment by eLRuLL** [comment]
right, not updating `NEWS` then. This PR could wait then after the release.

**Comment by robsonpeixoto** [comment]
Need to rebase this PR

**Pull request merged**
